### ISSUE TITLE
Rust cache action

### ISSUE THREAD

**Issue by zelytra** [zelytra/BetterFleet#53]
Add this to the CI to cache Rust compiation and increase build time:

```yaml
- uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.config.rust_target }}
```
